server:
  Port: 5000
  PprofPort: 5555
  AppVersion: 1.0.0 #Debug + tracking
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: false 
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

redis:
  RedisAddr: redis:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0
  
mysql:
  Host: docker.for.mac.localhost
  Port: 3306
  User: root
  Password: abc12345
  DtbName: qairline-dtb #Database name
  MaxIdleConns: 10
  MaxOpenConns: 10
  ConnMaxLifetime: 10

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expires: 3600

